examples/lastfm.py
Transform `data` or `X` to coo matrix right away and perform weighting using bm25.
=> Make bm25 weight function easier to read

implicit/als.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/recommender_base_test.py
Added functionality for filtering recommendations #26
=> added filtering functionality and corresponding tests

.travis.yml
use explicit pip2/pip3 (and python2/3). Also use newer OSX xcode image.
=> fix OSX travisci

implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/recommender_base_test.py
All recommenders can rank only selected items w.r.t the user.
This function will be useful in such case that "recommend an user only
10 movies among 200 horror movies in total 20,000 movies"
#89
=> Add rank_items method to recommender

examples/lastfm.py, examples/movielens.py, implicit/__init__.py, implicit/datasets/_download.py, implicit/datasets/lastfm.py, implicit/datasets/movielens.py, setup.py
Use the HDF5 file format for the example programs. This lets the example files
load substantially faster (20s -> 1s on my system).
Also add some code to automatically download these files if they are missing.
=> Use HDF5 files for examples

implicit/datasets/sketchfab.py
Add sketchfab dataset as described in http://blog.ethanrosenthal.com/2016/10/09/likes-out-guerilla-dataset/
=> add sketchfab dataset

implicit/datasets/reddit.py
Add a dataset of reddit votes, from https://www.reddit.com/r/redditdev/comments/bubhl/csv_dump_of_reddit_voting_data/
=>  add a reddit votes dataset

implicit/recommender_base.py
Tidying up recommend function.
=> Tidying up recommend function

implicit/recommender_base.py
Adding filter_already_liked_items to docstring.
=> Doc update - filter_already_liked_items

.travis.yml, implicit/nearest_neighbours.py, tests/approximate_als_test.py, tests/recommender_base_test.py
Add support for pickling knn models.
Also fix travisci build that was failing due to nmslib not installing w/ python2 anymore
=>  Add pickle support for nearest neighbours models 

implicit/als.py, implicit/bpr.cpp, implicit/bpr.pyx, implicit/lmf.cpp, implicit/lmf.pyx
Remove previous validation, and add automatic validation scheme
=> Remove previous validation, and add automatic validation scheme

implicit/__init__.py, implicit/als.py, implicit/bpr.pyx, setup.cfg, setup.py
=> hotfix to #286

examples/lastfm.py
=> Fix simple typo: utiliizing -> utilizing

cuda_setup.py
Support building on Cuda11 by dropping support for compute_30 devices.
=> Support building on Cuda11

implicit/cpu/matrix_factorization_base.py, implicit/gpu/knn.cu, implicit/gpu/matrix_factorization_base.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/recommender_base_test.py
=> Add filtering options for similar_users and similar_items

.pylintrc, implicit/cpu/als.py, implicit/gpu/als.py, tests/als_test.py
=> Fix ALS model when calculate_training_loss=True and iterations=0

.pre-commit-config.yaml, implicit/cpu/bpr.h, implicit/cpu/select.h, implicit/gpu/als.cu, implicit/gpu/als.h, implicit/gpu/bpr.cu, implicit/gpu/bpr.h, implicit/gpu/device_buffer.cu, implicit/gpu/device_buffer.h, implicit/gpu/knn.cu, implicit/gpu/knn.h, implicit/gpu/matrix.cu, implicit/gpu/matrix.h, implicit/gpu/random.cu, implicit/gpu/random.h, implicit/nearest_neighbours.h
Add clang-format to the pre-commit hooks, and apply to all the native files
=> clang-format

tests/als_test.py
Add a test for the ALS model to make sure we don't get NaN values when the number of
factors is larger than the number of items or users (#377).
=> Add unittest for NaNs occuring in ALS model

implicit/evaluation.pyx
Rather than calling model.recommend for each user, batch up requests into groups
of 1K users. This leads to to significant speedups: over 50x faster evaluation
on the GPU on both movielens20m and lastfm datasets, and over 10x faster evaluation
on the CPU.
=> Speedup evaluation by using batch recommend functions

implicit/evaluation.pyx
During evaluation, don't generate recommendations for users that
don't have any withheld items in the test set. Previously
we skipped  calculating the eval metrics for these users after generating
their recommendatiosn - which caused unnecessary work.
This moves the code to filter out users without any items in the test set
to before we generate recommendations for them,
=> Skip generating recs for missing users from test set

docs/source/conf.py, docs/source/index.rst, examples/tutorial_lastfm.ipynb
Adds a tutorial for the lastfm example, and links it into the sphinx docs
=> Add a tutorial notebook for the lastfm example

CHANGELOG.md, examples/lastfm.py, implicit/gpu/CMakeLists.txt
* Fix lastfm.py example for recommend
* Disable building GPU extension on windows
* Update changelog
=> Final updates for the 0.5.0 release

pyproject.toml
=> Build binary wheels for apple silicon

examples/lastfm.py, examples/movielens.py
Batch calls to similar_items in the movielens example script.
=> Use the batch functionality in the movielens example
