implicit/als.py, implicit/annoy_als.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/knn_test.py, tests/recommender_base_test.py
Hi Benfred,
Thanks so much for this library!
I'm not sure if you are aware, but it's a standard practice to [sample users to get item factors](https://www.quora.com/How-do-I-speed-up-matrix-factorization-by-sampling-users-without-losing-precision) and then use those vectors to generate recommendations for all users.
The trick is to cache item factors only and compute user vectors on the fly to generate recommendations. Another advantage of this approach is that we can recompute user recommendations as soon as we have more data, without needing to rebuild the whole model.
This is a rough implementation of the idea. It introduces the `recommend_from_liked` method that accepts a list of items that were consumed by the user.
I did not reuse the code that computes the user vector in the …
=> Recommend from liked

implicit/als.py, tests/als_test.py
Hi @benfred. I implemented another feature, for explaining recommendations.
The new method returns the items in the user history that contributed the most for a recommendation.
The equations for this are in section 5 of the http://yifanhu.net/PUB/cf.pdf
Would it make sense to add this? What do you think about the API?
=> Explain recommendations

tests/approximate_als_test.py, tests/recommender_base_test.py
Try to reduce the number of random unittest failures coming from
the approximate als methods.
=> Reduce random approximate_als unittest failures

examples/movielens.py, implicit/_als.cpp, implicit/_als.pyx, implicit/als.py, implicit/approximate_als.py, tests/recommender_base_test.py
There used to be problems with the movielens example, where
occasionally items with no users would be returned. Since these
items sometimes had no matching label, this would trip up the
code looking up the string to show (https://github.com/benfred/implicit/issues/59)
Fix this by detecting this case, and setting the factors to 0.
When returning similar items also make sure that we don't introduce
NaN values here.
=> Fixes for having no data on a user/item

examples/lastfm.py, examples/movielens.py, implicit/_als.cpp, implicit/_als.pyx, implicit/als.py, tests/recommender_base_test.py
Previously all the ALS based models expected sparse matrices with a dtype of
numpy.float64 - and would fail to run in cython code if passed a float32
matrix instead. Fix this to allow passing either matrix type, and default
to float32 since the extra precision won't help in the majority of cases.
=> Allow float32 inputs in ALS models

.gitignore, implicit/als.py, implicit/cuda/_cuda.cpp, implicit/cuda/_cuda.pyx, implicit/cuda/als.cu, implicit/cuda/als.h
CUDA version of the function to calculate_training_loss. Means that we
don't need to copy back to python during training, and is significantly faster.
=> CUDA calculate_training_loss function

.travis.yml, setup.py
Hi, this PR adds code that enables `setup.py` to find GOMP on macOS systems, so `pip install implicit` should just work on macOS. 
This also updates the Travis config to test on macOS - tests pass: https://travis-ci.org/stillmatic/implicit
=> allow macOS to find GOMP

examples/lastfm.py
Fixed `ValueError: negative row index found` for lastfm.py example which is occuring with 360K lastfm dataset from [there](http://www.dtic.upf.edu/~ocelma/MusicRecommendationDataset/lastfm-360K.html).
=> examples/lastfm.py: fix

setup.py
Use pandoc if it's installed to populate a long_description from the README.md,
and read version string from the python file (so that we don't have two
independent versions that need read in)
=> Tweak setup.py

implicit/_nearest_neighbours.cpp, implicit/_nearest_neighbours.pyx, implicit/nearest_neighbours.h, implicit/nearest_neighbours.py
Use the same sparse matrix multiplier infrastructure used in fitting the
KNN models to speed up recommendations. This leads to around a 10x
speedup in recommending items.
=>  Faster KNN recommendations

implicit/bpr.cpp, implicit/bpr.pyx
Scale randomly initialized factors by the number of factors we're using. This leads
to substantial improvements in cross validation metrics like P@10. Also
center factors while we are at it. This approached was inspired by lightfm, and with
this changes the xval results are basically identical between these two libraries
for their BPR models.
With a 16 factor BPR model and learning_rate= 0.005 there is a
noticeable increase in p@10 with this change:
| Dataset        | P@10 Before Change | P@10 After Change |
| -------------- | ------------------ | ----------------- |
| Movielens 100k | 0.164              | 0.228             |
| Movielens 1M   | 0.186              | 0.243             |
| Movielens 10M  | 0.159              | 0.185             |
| Movielens 20M  | 0.142              | 0.228 …
=> Better BPR Factor Initialization

implicit/_als.cpp, implicit/_als.pyx, implicit/als.py, implicit/cuda/als.cu, tests/als_test.py
With synthetic data and a large regularization parameter, the CG ALS model
would converge so that some users/items factors had 0 vectors for solutions.
The CG update would fail in this case setting all the factors to NaN. (https://github.com/benfred/implicit/issues/106).
Fix by detecting when this would occur and aborting. A previous
check handled the case inside the loop: https://github.com/benfred/implicit/issues/19#issuecomment-283164905
=> Extra NaN check for conjugate gradient ALS model

cuda_setup.py, setup.py
The check for the cuda lib64 directory was happening before it was properly
set: move the check to the correct place. Also remove unneeded
runtime_library_dirs option from build.
=> Fix issues with windows CUDA install

implicit/_als.cpp, implicit/_als.pyx, implicit/als.py, implicit/cuda/als.cu
Allow negative confidence values to be passed in, signifying that the user disliked the item. This lets us set higher confidence values for the known negatives.
Experiments here indicate setting known negatives to a higher confidence level slightly reduces p@10, but signifincantly reduces the likelihood of withheld negative items to be recommended: https://github.com/benfred/implicit/issues/114
=> Add option for negative preferences in ALS

implicit/evaluation.cpp, implicit/evaluation.pyx
In train_test_split function (in evaluation.pyx),
There is no filtering negative feedback there. This might make some (1) wrong predictions hit or (2) result lower recall score because of regarding uninteresting items as interesting ones.
=> Add filtering negative feedback in the test set

implicit/nearest_neighbours.py
_scorer_ is not initialized in the **ItemItemRecommender** _load_ function, so when calling _recommend_ after _load_  it throws AttributeError: 'NoneType' object has no attribute 'recommend'.
=> initialize scorer in ItemItemRecommender load function

implicit/nearest_neighbours.py, implicit/recommender_base.py
Issue #131  says recommending already seen items will be good in some situations.
=> Add an option to whether to include previously liked items or not

implicit/approximate_als.py
Slicing a big user_item array is very time consuming and make approximate-alternating least squares inference slower than regular Alternating Least Squares where recurrent recommendation is needed.
- This modification replicates AlternatingLeastSquares.recommend() logic.
=> Implement filter_already_liked_items option - Approximate-AlternatingLeastSquares - Issue #327

implicit/nearest_neighbours.py
The line `liked_vector = user_items[user_id]` loses information about the indices.
`recommendations.indices` returns a vector where all elements are zero `[0, 0,...,0]`.
This impacts the line `best = sorted(zip(recommendations.indices, recommendations.data), key=lambda x: -x[1])`.
If you run` rank_items(...)`, you will find the returned output looks like follows: `[(0, similarity), (0, similarity), (0, similarity)]`.
Fix here is to simply replace `user_items[user_id]` with `user_items.getrow(user_id)` which returns the same vector but retains information about the indices.
`recommendations.indices` will perform as expected returning a vector where all elements are indices e.g. `[0, 1,...,N]`.
=> Fix rank items in ItemItemRecommender

.travis.yml
OSX builds are failing on travis for python version 3. Attempt to fix.
Also move build matrix to python 3.7/3.8 and drop python 3.5
=> Attemp to fix travisci

implicit/cpu/bpr.cpp, implicit/cpu/bpr.pyx, implicit/lmf.cpp, implicit/lmf.pyx
the LMF/BPR models were converging to different results each time,
even when the random_state parameter was being passed in. The
problem was that each thread was getting a different set of rows each
time, which affected how negative samples were sampled.
Fix by using a static openmp schedule.
=> Fix random output with LMF/BPR models

implicit/gpu/als.py, implicit/gpu/bpr.py, implicit/gpu/utils.cuh
Our MF algorithms produced incorrect results when the number of factors
wasn't warp aligned (like a multiple of 32).
This fixes a problem where we weren't correctly calculating the number of
warps in the dot function - meaning that we weren't including the results
of the last partial warp in the reduction.
Closes #262
=> Fix GPU dot product when the # of factors wasn't warp aligned

implicit/gpu/als.cu, implicit/gpu/bpr.cu, implicit/gpu/utils.cuh, tests/als_test.py
Rather than calculate the dot product with shared memory, use registers
values of cooperating threads to store the partial results. Combined with
increasing the grid size, this leads to roughly a 15% performance improvement
in training time
=> Use gpu registers for dot product

.github/workflows/build.yml, implicit/gpu/_cuda.pyx, implicit/gpu/als.cu, implicit/gpu/als.h, implicit/gpu/als.pxd, implicit/gpu/als.py, implicit/gpu/bpr.cu, implicit/gpu/bpr.h, implicit/gpu/bpr.pxd, implicit/gpu/bpr.py, implicit/gpu/matrix.cu, implicit/gpu/matrix.h, implicit/gpu/matrix.pxd, implicit/gpu/utils.cuh
Rename the CUDA c++ classes  by removing the 'Cuda' / 'Cu' prefixes and move c++ classes into implicit::gpu namespace.
=> Rename cuda C++ classes

cuda_setup.py, examples/lastfm.py, implicit/cpu/bpr.pyx, implicit/datasets/lastfm.py, implicit/gpu/__init__.py, implicit/gpu/_cuda.pyx, implicit/gpu/als.py, implicit/gpu/bpr.cu, implicit/gpu/bpr.py, implicit/gpu/device_buffer.cu, implicit/gpu/device_buffer.h, implicit/gpu/knn.cu, implicit/gpu/knn.h, implicit/gpu/knn.pxd, implicit/gpu/matrix.cu, implicit/gpu/matrix.h, implicit/gpu/matrix.pxd, implicit/gpu/matrix_factorization_base.py, implicit/gpu/random.cu, implicit/gpu/random.h, implicit/gpu/random.pxd, implicit/gpu/utils.cuh, setup.py, tests/als_test.py, tests/gpu_test.py
Add a KnnQuery class for querying top-k related items on the GPU. This lets us remove
the cupy dependency, which for the small amount of functionality we need (top-k / random
/ matrix multiplication) required a 900+mb package to be installed.
Currently this is only slightly faster than the cupy version (20%) but will become faster
as we move towards batch processing and faster top-k selection algorithms for small k.
=> Add custom GPU inference code / remove cupy dependency

implicit/gpu/knn.cu, implicit/gpu/knn.h, implicit/gpu/matrix_factorization_base.py
Add a basic top-k algorithm using cub BlockRadixSort. Sort a series of
1024 element blocks with cub, and take the top K from each block repeating until
there is only 1 block to sort. On a single item this increases queries to around
3K QPS on the lastfm dataset, and using batch queries can get up to 25K QPS.
=> Block radix select

cuda_setup.py
We were picking up the system nvcc (installed to /usr/local/cuda/bin) instead
of just using the nvcc on the path. This caused issues with newer conda builds
on conda-forge. Fix.
=> Use nvcc from the path

benchmarks/benchmark_als.py, implicit/cpu/als.py, implicit/gpu/als.py
I am running implicit als inside a Docker container as a custom AWS SageMaker algorithm. As it is now, the loss during fit iterations is not picked up as a metric properly by the SageMaker log parser when the loss is outputted using tqmd (which has a funky output format). This PR adds an optional parameter (default False) to the als fit function to also output each loss as a regular info log. This would make it possible for AWS SageMaker to pick up loss during iterations as a metric from the regular info logs.
What do you think about the idea to optionally output plain info logs?
Ideally I would like to choose either tqmd or plain info logs, but to my understanding if show_progress is False the whole function call will be skipped. So outputting individual info logs would only work when …
=> Optionally output iteration loss as info log

implicit/gpu/knn.cu, implicit/gpu/matrix_factorization_base.py, tests/als_test.py
We had an issue where we were filtering out scores < 0 in the gpu code,
which caused a bug in the gpu test_rank_items code for ALS. Fix, and
ensure that the unittest is actually working on the GPU
=> Fix als test_rank_items on GPU

.github/workflows/build.yml, implicit/gpu/matrix_factorization_base.py, tests/als_test.py, tests/approximate_als_test.py, tests/bpr_test.py, tests/knn_test.py, tests/lmf_test.py, tests/recommender_base_test.py
Switch over to rely more on pytest for parameterizing tests, instead of
defining all the different parameters in a loop in the ALS tests
=> Switch to using pytest parameterize in als/bpr tests

setup.py, tests/approximate_als_test.py
We were getting an error like  ```error: don't know how to compile C/C++ code on platform 'posix' with 'nvidia' compiler```
when compiling. This seems to be the same error as seen here https://github.com/cupy/cupy/issues/5476.
Fix by importing numpy.distutils before doing any setuptools imports.
Closes #499
=> Build fix for setuptools > 60.0

.github/workflows/build.yml, .pylintrc, implicit/ann/annoy.py, implicit/ann/faiss.py, implicit/ann/nmslib.py, implicit/approximate_als.py, implicit/utils.py, setup.py, tests/approximate_als_test.py, tests/recommender_base_test.py
Approximate nearest neighbours used to only work for the ALS mode on the CPU.
This change makes it so that we can compose ANN methods with any matrix factorization
model (including BPR/LMF) and also use the GPU MF models as well.
Currently this provides the same api in implicit/approximate_als.py for backwards
compatability - but this may be removed at a future date.
Closes #487
=> Make approximate nearest neighbours models composable.

.pylintrc, implicit/ann/annoy.py, implicit/ann/faiss.py, implicit/ann/nmslib.py, implicit/cpu/matrix_factorization_base.py, implicit/gpu/matrix_factorization_base.py, implicit/nearest_neighbours.py, tests/recommender_base_test.py
If user_items isn't a CSR matrix in the recommend call then wrong results will get returned with
filter_already_liked_items or recalculate_user options.
Closes #365
=> Check user_items is a CSR matrix in recommend

implicit/cpu/matrix_factorization_base.py, implicit/gpu/matrix_factorization_base.py, tests/recommender_base_test.py
When using the 'items' filter on the recommend calls, we had two
different bugs in the latest code. One was that if you specified
a 'N' value greater than the size of the items you were ranking,
the results contained invalid values. The other was that we weren't
properly handling the 'filter_already_liked' option when the 'items'
option was set for MF models. Fix and add a unittest that would have
caught this
=> Fix for recommend with 'items' filter

.gitmodules, MANIFEST.in, implicit/gpu/CMakeLists.txt
Use rapids-cmake for including FAISS, rather than checout w/ a git submodule.
Using rapids-cmake will also make including RMM/Raft (in a future pr) much easier.
=> Use rapids-cmake for including FAISS

implicit/cpu/_als.pyx, implicit/cpu/als.py, implicit/cpu/matrix_factorization_base.py, implicit/gpu/_cuda.pyx, implicit/gpu/als.cu, implicit/gpu/als.h, implicit/gpu/als.pxd, implicit/gpu/als.py, implicit/gpu/matrix_factorization_base.py, tests/recommender_base_test.py
Add GPU support for recalculating items and users factors at inference time.
Also speed up the CPU versions by using the native solver rather than the
python version.
=> Add support for recalculate_users/items on the GPU

implicit/cpu/als.py, implicit/gpu/_cuda.pyx, implicit/gpu/als.py, implicit/gpu/knn.cu
* Fix OOM that could happen on the GPU topk when tiling rows
* Don't bother randomly initializing factors in recalculate_users/items
* Rather than only use 500MB for GPU temp memory, have it dynamic based off free mem
=> Minor GPU fixes

implicit/_nearest_neighbours.pyx, implicit/cpu/_als.pyx, implicit/evaluation.pyx
On the CPU, we were not achieving full thread utilization. The problem seems to be that
using the 'guided' schedule in openmp assigns a large range of ids to a single thread,
and its pretty common to have ids sorted by frequency. This caused 1 thread to process
all the high activity users/items - and left the others starved for work as they finished
early.
Fix by switching to a dynamic openmp schedule. For the ALS model on cpu, this change is 3.8x
faster on training movielens-20m, and 2.2x faster training the Github Stars dataset -
while being neutral  on lastfm. For the cosine model, this change is 2.2x training movielens20m.
* 'schedule=dynamic' times:
* ALS model:
* GitHub 60.96 s/it
* Movielens: 1.05 it/s
* LastFM 2.19 s/it
* Cosine model:
* Movielens: 49603.48 it/s
* …
=> Multithreaded speedups for CPU models.

examples/lastfm.py, examples/movielens.py, implicit/gpu/__init__.py, implicit/gpu/_cuda.pyx, implicit/gpu/als.cu, implicit/gpu/bpr.cu, implicit/gpu/dot.cuh, implicit/gpu/knn.cu, implicit/gpu/matrix.cu, implicit/gpu/random.cu, implicit/gpu/utils.h, implicit/gpu/utils.pxd
Rather than just relying on the _cuda extension being built, also
check to see if we have valid GPU devices. If there aren't
GPU devices available, a warning saying:
``` 
UserWarning: CUDA extension is built, but disabling GPU support because of 'Cuda Error:
no CUDA-capable device is detected
```
will be logged, and GPU compatability disabled.
=> Dynamically detect CUDA availability

implicit/cpu/als.py, implicit/cpu/bpr.pyx, implicit/gpu/als.py, implicit/gpu/bpr.py, tests/gpu_test.py
Adds some simple methods to convert BPR and ALS models from a CPU version
to a GPU version. This is useful for when you want to train on the CPU
and evaluate on the GPU (or vice versa).
=> Add methods for converting MF models to/from gpu

implicit/ann/annoy.py, implicit/ann/faiss.py, implicit/ann/nmslib.py, implicit/cpu/als.py, implicit/cpu/matrix_factorization_base.py, implicit/datasets/lastfm.py, implicit/datasets/movielens.py, implicit/gpu/als.py, implicit/gpu/matrix_factorization_base.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/recommender_base_test.py
On the model.recommend we pass 'user_items' sparse matrix, but on the
model.similar_items call we had a 'react_users' sparse matrix. Rename
this parameter to 'item_users' to be consistent
=> Rename react_users to item_users

implicit/gpu/bpr.cu
Use thrust::binary_search to verify negative samples on the GPU instead of
doing a linear scan in the BPR model.
This leads to a noticeable perf increase on larger datasets. For instance on the
Github stars dataset:
* Using linear_search: 3.09s/it
* using thrust::binary_search 1.53s/it
* w/ verify_negative_samples=False  1.18s/it
This change doubles the BPR training performance on that dataset, and also
leads to times that are only 30% slower than not verifying samples at all.
=> Use thrust::binary_search to verify negative samples on GPU

README.md, docs/source/index.rst, implicit/_nearest_neighbours.pyx, implicit/ann/annoy.py, implicit/ann/faiss.py, implicit/ann/nmslib.py, implicit/cpu/als.py, implicit/cpu/matrix_factorization_base.py, implicit/evaluation.pyx, implicit/gpu/als.py, implicit/gpu/matrix_factorization_base.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, implicit/utils.py, tests/als_test.py, tests/gpu_test.py, tests/recommender_base_test.py
In the recommend call, user_items required empty rows to be passed for users that
weren't being recommended - and likewise the similar_items had a item_users param
with the same restriction. When generating recommendations for a single user,
if the userid is large - we'd have to generate a vector with an entry for each smaller userid.
Change this to use the passed in 'userid' array, and just have the rows in the user_items
sparse matrix match those in the userid array.
=> Don't require empty rows in user_items and item_users

implicit/cpu/als.py, implicit/gpu/_cuda.pyx, implicit/gpu/als.cu, implicit/gpu/als.py, implicit/gpu/matrix.cu, implicit/gpu/matrix.h, implicit/gpu/matrix.pxd, tests/als_test.py, tests/approximate_als_test.py
This change adds a 'partial_fit_users' and a 'partial_fit_items' methods to the ALS
models, that lets you incrementally retrain the model. This both lets you add
new items and users to the model without fully retraining, as well as recalculate
existing item/users with new interactions.
=> Add incremental retraining support for ALS models

implicit/gpu/_cuda.pyx
Previous code was holding on the GIL when training models on the GPU
or when calculating results. This caused some jank on progress bars
displaying in jupyter notebooks, as well as just being poor form.
Fix by releasing the GIL before starting on gpu code that will take
an appreciable amount of time.
=> Release GIL on GPU calls

implicit/gpu/knn.cu
In certain cases we could get an OOM on inference on the GPU models.
Fix by calculating the temp memory appropriately.
=> Fix temp memory calculation on GPU

CMakeLists.txt, setup.py
The FindCUDAToolkit module was introduced in cmake v3.17 - add that
as a minimum cmake version
=> Require cmake v3.17+

pyproject.toml, requirements-dev.txt
We were using the latest git version of scikit-build, since the
0.12 release didn't have support for docstrings in cython.
Now that scikit-build 0.13 is out, this is no longer necessary. switch
to using the stable release version.
=> Use scikit-build>=0.13.1

docs/source/conf.py, implicit/als.py, implicit/ann/annoy.py, implicit/ann/faiss.py, implicit/ann/nmslib.py, implicit/cpu/als.py, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/gpu/als.py, implicit/gpu/bpr.py, implicit/gpu/matrix_factorization_base.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/approximate_als_test.py, tests/recommender_base_test.py
Add support for serializing models to .npz files. Closes #541
=> Add save/load functions for models

.pre-commit-config.yaml, implicit/ann/annoy.py, implicit/gpu/CMakeLists.txt, implicit/gpu/bpr.py, implicit/gpu/matrix_factorization_base.py, implicit/nearest_neighbours.py, implicit/utils.py, requirements-dev.txt
Add an option to build implicit without the GPU extension, if the IMPLICIT_DISABLE_CUDA environment variable
is set. Closes https://github.com/benfred/implicit/issues/446
=> Disable building GPU extension if IMPLICIT_DISABLE_CUDA env var is set

implicit/cpu/als.py, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/cpu/matrix_factorization_base.py
For the MF models on the CPU, there didn't use to be a way to
control how many threads were used during batch .recommend calls.
Re-use the num_threads parameter for this, to allow using only
a limited number of threads for calculating batch recommendation
calls.
Closes #554
=> Use num_threads for batch recommendations in MF models

implicit/cpu/als.py, implicit/gpu/als.py, tests/als_test.py
When trying to update with exactly 1 new item, partial_fit_items would
throw an exception since we had an off-by-one error in allocating
factor storage. Fix and add a unittest that would catch this.
Closes #556
=> Fix partial_fit_items bug with only growing by a single item

implicit/_nearest_neighbours.pyx, implicit/cpu/als.py, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/gpu/als.py, implicit/gpu/bpr.py, implicit/utils.py, pyproject.toml, tests/recommender_base_test.py
Previously we allowed non-csr inputs to the ALS models, but would fail
if a non-csr matrix was passed to the BPR model.fit. Change to be consistent
in allowing, but warn if we are based a COO or LIL matrix instead of the CSR
matrix we expect.
=> Warn on non-csr input passed to model.fit

examples/tutorial_lastfm.ipynb, implicit/als.py, implicit/cpu/als.py, implicit/gpu/als.py, tests/als_test.py
This adds an alpha parameter to the ALS models - which is the weight each
positive example is multiplied by. While we could previously achieve the
same result before by passsing a sparse matrix to model.fit where the weight
was already multiplied in, having as an explicit parameter makes it easier
to work with hyper parameter tuning frameworks - letting you treat the same
as things like regularization/epochs etc
=> Add an `alpha` parameter for the ALS models

implicit/cpu/bpr.pyx, implicit/gpu/bpr.py
In the BPR model, we only need sorted indices in the CSR matrix input
to verify negative samples. Change to not sort the indices when we're
not verifying negative samples.
=> Only call sort_indices when verifying negative samples

implicit/gpu/als.py, tests/als_test.py
The recalculate_user or recalculate_item functionality didn't work on the GPU
AlternatingLeastSquares model, if the model was created from a saved version
of converted from a CPU model. Fix and add a unittest that would have caught this
Fixes #597
=> Fix `recalculate_user` / `recalculate_user` on the GPU

implicit/gpu/_cuda.pyx, implicit/gpu/als.cu, implicit/gpu/bpr.cu, implicit/gpu/knn.cu, implicit/gpu/matrix.cu, implicit/gpu/matrix.h, implicit/gpu/matrix.pxd, implicit/gpu/random.cu, implicit/gpu/random.h, implicit/gpu/random.pxd
We had some issues that prevented us from learning models with more than
2**31 parameters in one of the matrices (so ~8GB of total space). This
was because we were using int32 to represent the rows/cols - and
when multiplying together we'd overflow.
Fix by using size_t. Have manually verified I can train a model with
over 25M users and 128 factors with this change (both bpr & als).
=> Handle more than 2**31 parameters on GPU models

implicit/gpu/matrix.cu
Use CUDA Unified Virtual Memory for sparse matrices on the GPU. This allows GPU models to train on
input sparse matrices that exceed the size of GPU memory, by letting cuda page data to/from host memory using UVM.
This has been tested on a ALS model with around 2B entries in the spare matrix, on a GPU with 16GB of memory. Previously this OOM'ed since we need around 32GB of GPU memory to store the sparse matrix and its transpose, but with this change training succeeded - and was around 20x faster on the GPU than on the CPU.
=> Allow GPU models to train on sparse matrices that exceed the size of available GPU memory

implicit/ann/annoy.py, implicit/ann/faiss.py, implicit/ann/nmslib.py, implicit/cpu/als.py, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/gpu/als.py, implicit/gpu/bpr.py, implicit/nearest_neighbours.py, implicit/recommender_base.py, tests/bpr_test.py, tests/recommender_base_test.py
* Rename the 'fit_callback' parameter on the '.fit' method to just
'callback' (since the fit_ is redundant)
* Update fit method signatures of subclasses like the ANN models and ItemItem models to
be consistent with the base class
* fix issue in implicit/cpu/als.py where the callback parameter wasn't being used, and add
a unittest that tests this
=> Tweak callback API

.pylintrc, implicit/_nearest_neighbours.pyx, tests/recommender_base_test.py
https://github.com/benfred/implicit/pull/482 introduced a bug where the output of the knn models wasn't strictly ordered by score.
Fix this and add a test that would have caught this bug
=> Fix ordering in .recommend for KNN models

implicit/_nearest_neighbours.pyx, implicit/nearest_neighbours.py
Remove `int u ` argument in recommend() method in NearestNeighboursScorer
#610
=> Remove unnecessary argument

implicit/gpu/matrix_factorization_base.py, tests/recommender_base_test.py
GPU models weren't default initializing members like _knn appropriately when being loaded from pickle appropriately. Fix and update the unittest to test this out.
=> Fix pickling GPU models

implicit/cpu/topk.pyx, implicit/gpu/als.pxd, implicit/gpu/als.py, implicit/gpu/matrix.cu, implicit/gpu/matrix_factorization_base.py, tests/als_test.py
The last round of fixes didn't properly save parameters (like regularization etc)
on the ALS models - and just relied on the default. Fix.
Also, add another unittest for pickling ALS models, testing that we can call 
`.recalculate_user` after pickling and get the same result, and fix the
errors that this highlighted.
=> Fix more issues with pickling GPU models

setup.py
It's deprecated, and was only put in place to work around build issues with setuptools that seem to be resolved
=> Remove import of numpy.distutils

implicit/cpu/_als.pyx, tests/als_test.py
We weren't calculating the loss correctly for CPU ALS models, when regularization was non-zero. In addition to incorrect results, this also could cause a segfault in certain conditions.
Fix.
=> Fix for ALS calculate_loss on the cpu

implicit/cpu/_als.pyx, implicit/cpu/als.py, implicit/gpu/als.cu, implicit/gpu/als.py, tests/als_test.py
The GPU ALS model would sometimes return incorrect results with the `calculate_training_loss` parameter enabled. This happend when the number_of_users * number_of_items was bigger than 2**31 due to an overflow in the loss function calculation.
Fix and add tests that would have caught this bug
Closes https://github.com/benfred/implicit/issues/367 
Closes https://github.com/benfred/implicit/issues/441
=> Fix ALS loss calculation on GPU

implicit/CMakeLists.txt, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/evaluation.pyx
Set cython directives like `language_level=3` and `embedsignature=True` globally, so that they are applied to all the cython files, rather than manually in each one. This removes a bunch of build warnings about not specifying a language_level while building
=> Set cython directives globally

implicit/_nearest_neighbours.pyx, implicit/gpu/CMakeLists.txt
The conda-forge build was failing to build on errors in finding thrust: https://github.com/NVIDIA/thrust/issues/1966
Work around this issue by using a patched version of thrust/cub in the build
=> Fix cuda build on conda-forge

implicit/cpu/_als.pyx, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/cpu/topk.pyx
This fixes a large performance regression with many of the CPU models.
For instance when training the ml100k dataset, when compiled with Cython 3.0.0:
* Without this change
```
DEBUG:implicit:trained model 'bpr' in 69.49404716491699
DEBUG:implicit:trained model 'lmf' in 42.24160981178284
DEBUG:implicit:trained model 'als' in 120.11413407325745
```
* With this change
```
DEBUG:implicit:trained model 'bpr' in 0.18895816802978516
DEBUG:implicit:trained model 'lmf' in 0.06523633003234863
DEBUG:implicit:trained model 'als' in 1.8809657096862793
```
Fixes #678
=> Add `noexcept` declarations for Cython 3.0

implicit/gpu/CMakeLists.txt, implicit/gpu/knn.cu, implicit/gpu/knn.h
Update to use the latest raft version. RAFT 23.08 includes a sort option as part of the select_k method https://github.com/rapidsai/raft/pull/1615 which means we don't have to sort the output ourselves.
=> use raft 23.08

implicit/cpu/als.py, implicit/gpu/_cuda.pyx
We were seeing some poor result on partial_fit_*, that ended up caused by passing a CSC instead of a CSR matrix.  (#682)
Add the same `check_csr` code to the partial_fit methods that is already done in the fit method - this will warn if passed a non-csr matrix, and automatically convert.
=> Add check_csr for partial_fit methods

implicit/cpu/als.py, implicit/gpu/als.py
The item_norms/user_norms were incorrect, especially for new items, after calling the partial_fit methods. Fix.
=> Clear cached properties on partial_fit_*

implicit/utils.py, requirements.txt, setup.py
We were using numpy.__config__.get_info to figure out what BLAS library was being used, in an effort to warn people if they hadn't disabled the internal threadpool for the BLAS they were using. This method is removed in numpy 1.26, causing errors.
Fix by using the threadpoolctl library to detect both the BLAS library and the number of threads its configured for.
While we could automatically configure the BLAS library to reduce the threadpool size to 1, this is process wide - and would have side effects for our users. Instead just warn here, and give instructions for people on how to configure themselves.
=> use threadpoolctl for detecting BLAS threadpools

implicit/cpu/als.py, implicit/cpu/bpr.pyx, implicit/cpu/lmf.pyx, implicit/evaluation.pyx, implicit/gpu/bpr.py, implicit/gpu/matrix_factorization_base.py, implicit/utils.py, pyproject.toml, setup.py, tests/als_test.py, tests/bpr_test.py, tests/gpu_test.py
Replace RandomState with random.Generator for generating random numbers. The RandomState is marked as a legacy api, and will have no further improvements made to it. The Generator API also gives us some extra features, like the ability to specify dtypes rather than converting after the fact etc.
=> Use np.random.Generator for rng
